language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6.9.4'
before_install:
  - npm install -g rollup
install:
  - npm install
script:
  - npm run validate -s
after_success:
  - npm run coverage -s
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/